/*
 * Vencord, a Discord client mod
 * Copyright (c) 2025 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import { definePluginSettings } from "@api/Settings";
import { Logger } from "@utils/Logger";
import definePlugin, { OptionType, StartAt } from "@utils/types";

const logger = new Logger("ChatThemeColor", "#a78bfa");

// ─── Style injection ──────────────────────────────────────────────────────────

const STYLE_ID = "vc-chat-theme-color-style";

function getOrCreateStyle(): HTMLStyleElement {
    let el = document.getElementById(STYLE_ID) as HTMLStyleElement | null;
    if (!el) {
        el = document.createElement("style");
        el.id = STYLE_ID;
        document.head.appendChild(el);
    }
    return el;
}

function removeStyle() {
    document.getElementById(STYLE_ID)?.remove();
}

// ─── CSS builder ──────────────────────────────────────────────────────────────

function buildGradientValue(
    type: "solid" | "linear" | "radial",
    colorTop: string,
    colorMiddle: string,
    colorBottom: string,
    angle: number,
    useMiddle: boolean,
): string {
    if (type === "solid") {
        return colorTop;
    }

    if (type === "radial") {
        if (useMiddle) {
            return `radial-gradient(ellipse at center, ${colorTop} 0%, ${colorMiddle} 50%, ${colorBottom} 100%)`;
        }
        return `radial-gradient(ellipse at center, ${colorTop} 0%, ${colorBottom} 100%)`;
    }

    // linear
    if (useMiddle) {
        return `linear-gradient(${angle}deg, ${colorBottom} 0%, ${colorMiddle} 50%, ${colorTop} 100%)`;
    }
    return `linear-gradient(${angle}deg, ${colorBottom} 0%, ${colorTop} 100%)`;
}

function buildCSS(
    type: "solid" | "linear" | "radial",
    colorTop: string,
    colorMiddle: string,
    colorBottom: string,
    angle: number,
    useMiddle: boolean,
    opacity: number,
    coverMode: "chat" | "full",
): string {
    const gradient = buildGradientValue(type, colorTop, colorMiddle, colorBottom, angle, useMiddle);
    const alpha = (opacity / 100).toFixed(3);

    const isSolid = type === "solid";

    const chatTarget = `
/* ── ChatThemeColor: chat area ─────────────────────────── */
[class*="messagesWrapper_"],
[class*="chatContent_"] {
    background: ${gradient} !important;
    opacity: ${alpha};
}
[class*="messagesWrapper_"]::before,
[class*="chatContent_"]::before {
    content: none !important;
}`;

    const fullTarget = `
/* ── ChatThemeColor: full Discord ─────────────────────── */
#app-mount {
    background: ${gradient} !important;
}
#app-mount::before {
    content: "";
    position: fixed;
    inset: 0;
    z-index: -1;
    pointer-events: none !important;
    background: ${isSolid ? "transparent" : gradient};
    opacity: ${alpha};
}
[class*="sidebar_"],
[class*="panels_"],
[class*="content_"],
[class*="chat_"],
[class*="base_"],
[class*="container_"] {
    background-color: transparent !important;
}
[class*="attachment_"],
[class*="embed_"],
[class*="popout_"],
[class*="modal_"],
[class*="menu_"],
[class*="tooltip_"] {
    background-color: var(--background-secondary) !important;
}`;

    const target = coverMode === "chat" ? chatTarget : fullTarget;

    return [
        "/* Generated by ChatThemeColor — Vencord */",
        `:root { --ctc-gradient: ${gradient}; --ctc-opacity: ${alpha}; }`,
        target,
        "/* ─────────────────────────────────────────────────── */",
    ].join("\n");
}

// ─── Settings ─────────────────────────────────────────────────────────────────

const settings = definePluginSettings({
    gradientType: {
        type: OptionType.SELECT,
        description: "Tipe warna/gradient",
        options: [
            { label: "Solid (satu warna)", value: "solid", default: true },
            { label: "Linear (garis lurus)", value: "linear" },
            { label: "Radial (dari tengah ke luar)", value: "radial" },
        ] as const,
        onChange: () => applyTheme(),
    },

    colorTop: {
        type: OptionType.STRING,
        description: "Warna Atas (atau warna utama jika Solid) — format HEX",
        default: "#5865f2",
        placeholder: "#5865f2",
        onChange: () => applyTheme(),
    },

    useMiddleColor: {
        type: OptionType.BOOLEAN,
        description: "Aktifkan warna Tengah (3-stop gradient)",
        default: false,
        onChange: () => applyTheme(),
    },

    colorMiddle: {
        type: OptionType.STRING,
        description: "Warna Tengah (hanya berlaku jika 'Warna Tengah' diaktifkan)",
        default: "#9b59b6",
        placeholder: "#9b59b6",
        onChange: () => applyTheme(),
    },

    colorBottom: {
        type: OptionType.STRING,
        description: "Warna Bawah — format HEX",
        default: "#2c3e50",
        placeholder: "#2c3e50",
        onChange: () => applyTheme(),
    },

    angle: {
        type: OptionType.SLIDER,
        description: "Sudut gradient Linear (0° = bawah ke atas, 90° = kiri ke kanan, 180° = atas ke bawah)",
        default: 180,
        markers: [0, 45, 90, 135, 180, 225, 270, 315, 360],
        stickToMarkers: false,
        onChange: () => applyTheme(),
    },

    opacity: {
        type: OptionType.SLIDER,
        description: "Opacity warna theme (0 = transparan, 100 = penuh)",
        default: 80,
        markers: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
        stickToMarkers: false,
        onChange: () => applyTheme(),
    },

    coverMode: {
        type: OptionType.SELECT,
        description: "Area yang diberi warna",
        options: [
            { label: "Chat saja (area pesan)", value: "chat", default: true },
            { label: "Seluruh tampilan Discord", value: "full" },
        ] as const,
        onChange: () => applyTheme(),
    },
});

// ─── Core logic ───────────────────────────────────────────────────────────────

function applyTheme() {
    const {
        gradientType,
        colorTop,
        colorMiddle,
        colorBottom,
        angle,
        useMiddleColor,
        opacity,
        coverMode,
    } = settings.store;

    const css = buildCSS(
        gradientType ?? "solid",
        colorTop ?? "#5865f2",
        colorMiddle ?? "#9b59b6",
        colorBottom ?? "#2c3e50",
        angle ?? 180,
        useMiddleColor ?? false,
        opacity ?? 80,
        coverMode ?? "chat",
    );

    getOrCreateStyle().textContent = css;
    logger.info("Theme diterapkan.");
}

// ─── Plugin definition ────────────────────────────────────────────────────────

export default definePlugin({
    name: "chatThemeColor",
    description:
        "Atur warna atau gradient kustom untuk background chat Discord. " +
        "Support solid, linear gradient, dan radial gradient. " +
        "Atur warna atas, tengah, bawah, sudut, dan opacity.",
    tags: ["Appearance", "Customisation", "Theme", "Color"],
    authors: [{ name: "kintil555", id: 0n }],

    settings,
    startAt: StartAt.DOMContentLoaded,

    start() {
        applyTheme();
    },

    stop() {
        removeStyle();
    },
});
